### ISSUE TITLE
Issues with GitHub Dark theme

### ISSUE THREAD

**Issue by IceCreamYou** [irek02/chrome-github-code-review#6]
Nice work Irek 😀 

I use the [GitHub Dark theme](https://github.com/StylishThemes/GitHub-Dark) so that I don't spend hours staring at bright white light. With this theme two issues become apparent:
- Even when the sidebar is closed, there is a thin white bar on the right side of the screen. It doesn't really obscure anything, it just looks weird. (See first image)
- When the sidebar is expanded, it's hard to see the file/folder names because the contrast is low due to the Dark theme's light-colored text. (See second image)

![image](https://cloud.githubusercontent.com/assets/203177/16160451/16ef9fd4-347d-11e6-9dfc-3701e2c5e2ef.png)
![image](https://cloud.githubusercontent.com/assets/203177/16160482/410f7b72-347d-11e6-8c6d-4ea683455b1c.png)

**Comment by irek02** [comment]
Thanks @IceCreamYou! I'll be spending some time on this soon!

**Comment by irek02** [comment]
I made the extension to assign the background color for the sidebar based on the general theme color. Hope that helps!
